confidence: "invalid"
theme: 123

labels:
  bug: critical
  security: critical

rules:
  - match: "crash|broken"
    add: "should-be-array"
  - wrongkey: true

duplicates:
  enabled: "yes"
  threshold: 5
