confidence: 0.6
users:
  - gr2m
  - dancer
  - aayush-kapoor
  - lgrammel
  - nicoalbanese
  - felixarntz
prompt: >-
  - area labeling: ai/core covers core APIs (generateText, generateObject,
  streamText, streamObject, tool calling, structured output, steps, middleware,
  telemetry hooks) and any OpenAI Responses API structured outputs; ai/ui,
  ai/ui-vue, ai/rsc, ai/provider, ai/mcp, ai/gateway, ai/telemetry, ai/codemod,
  expo, tools-registry, codex as before.

  - provider labeling: assign ai/provider plus the specific provider label
  (e.g., provider/openai) for provider-specific issues; also keep
  provider/openai-compatible, provider/community, and the audio/speech provider
  labels as defined.

  - type labeling: bug, feature, documentation, maintenance, support, wontfix,
  deprecation as defined.

  - triage labels: reproduce-needed, reproduce-provided, pull-request-welcome,
  good-first-issue, external, resumability as defined.

  - version labels: major, minor, backport as defined.

  - workflow labels: type:batch, type:epic as defined.

  - labeling patterns: when the issue concerns core API functionality or OpenAI
  Responses API structured outputs, include ai/core; if it also concerns a
  provider, include ai/provider and the provider/<name> label. For example: “Add
  support for OpenAI Responses API structured outputs” should be ai/core,
  ai/provider, provider/openai.

  - do not assign labels you are not confident about; under-labeling is better
  than mislabeling.
