confidence: 0.6
theme: mono
labels:
  bug: critical
  security: critical
  p0: critical
  p1: high
  p2: medium
  feature: medium
  enhancement: medium
  documentation: muted
  config: medium
  webhook: medium
  github-api: medium
  maintenance: light
  duplicate: muted
  good-first-issue: muted
  help-wanted: muted
rules:
  - match: crash|broken|not working
    add:
      - bug
      - p1
  - match: security|vulnerability|cve
    add:
      - security
      - p0
  - match: docs|readme|typo
    add:
      - documentation
  - match: config|yaml|yml
    add:
      - config
  - match: webhook|payload
    add:
      - webhook
reactions:
  start: eyes
duplicates:
  enabled: true
  threshold: 0.8
  label: duplicate
  comment: true
ignore:
  users:
    - dependabot
    - renovate
autorespond:
  enabled: true
  label: needs-info
  context: |
    tigent is a github bot that auto-labels issues and prs.
    common issues involve webhook configuration and yaml syntax.
  requirements:
    bug:
      - steps to reproduce
      - expected vs actual behavior
      - environment info
    feature:
      - use case description
      - proposed solution
    default:
      - clear description
  message: |
    thanks for opening this issue! we need a bit more info to help you.
stale:
  enabled: true
  days: 30
  close: 7
  exempt:
    labels:
      - security
      - p0
      - p1
    assignees: true
  label: stale
  message: >
    this issue has been inactive for 30 days and will be closed in 7 days if
    there is no activity.
  closemessage: |
    closed due to inactivity. feel free to reopen if still relevant.
sentiment:
  enabled: true
  detect:
    negative: true
    frustrated: true
    confused: true
  triggers:
    issues: true
    comments: true
  noreply:
    enabled: true
    hours: 48
    mode: both
  labels:
    negative: needs-attention
    frustrated: needs-support
    confused: needs-help
    noreply: awaiting-response
  actions:
    comment:
      enabled: true
      negative: |
        we hear you and are looking into this.
      frustrated: |
        sorry for the frustration - we're on it!
      confused: |
        let us help clarify - we'll follow up shortly.
      noreply: |
        apologies for the delay - the team has been notified.
  threshold: 0.7
  exempt:
    labels:
      - wontfix
      - duplicate
    users: []
examples:
  - title: memory leak in websocket connections
    labels:
      - enhancement
